### ISSUE TITLE
suggestions for increasing data quality

### ISSUE THREAD

**Issue by othmar52** [usercamp/midi#62]
@benjaminfox  Thanks for your approach for building this great resource!

As i have integrated an old iPad for audio routing in my pcless synth setup your CSV's seems to be a great addition for my tiny webgui.
So i have added a few devices that did not exist in your database.

I noticed 2 things that can be improved in standardisation within your database:

# Formatting specific CC values/ranges with special meaning
My effort to parse and render the csv files is not that bad. But there are a lot of different data formats in the `notes` column which can't be parsed with javascript in a relieable way. Further the `notes` column may hold real notes instead of CC values/ranges  

I think it would make sense to put those values in a separate column which requires a special format (unified delimiters) to be able to parse the data in a relieable way.

Some examples of variations:
```
0:Sine 1:Tri 2:Saw 3:Square 4:S&H 5:S&G
0-31: -24LPF; 32-63: -12LPF; 64-95: -12BPF; 96-127: -12HPF
0 to 31: off; 32 to 63: ring; 64 to 95: sync; 96 to 127: ring sync
0-41 Retrig / 42-83 Free / 84-127 Single
0-63 for off; 64-127 for on
0-42 for low; 43-84 for high; 87-127 for last. Default is last.
0: 16', 32: 8'; 64: 4'; 96: 2'
<63=OFF; >64=ON
0=24db; 127=12db
.. and a lot more variations...
```
As you can see there are so much different delimiters (`;` `,` ` ` `/` ` for ` `:` `=`) in the existing CSV files.  
What do you think about moving those values to a separate column (for now i don't have a good idea for a name) with unified formatting instructions?  
Or do you think this is an overhead without that much benefit?  

# Tons of variations in categories/sections

In my additions i have tried to find some orientation in existing csv files for the column `sections`.  
So basically i used `General`, `Oscillators`, `Filter`, `Envelopes`, `Mix`, `FX`.  

Digging deeper in the rest of the database there are a lot of variations and depths as well:  
For example: `OSC 1` `Amp` `LFO 1` `Delay FX` `VCA Envelope`,...  
Maybe it make sense to add an optional column `subsection` to all csv files to increase the data quality and extend the possibilities for rendering the data!?  

Or do you think this would be an overhead without benefit as well?  

Anyway. Even without those 2 improvements your resource is great!  
thanks again

_EDIT_  
with unified delimiters in `notes` column something like this is possible  
<a href="https://othmar52.github.io/matrix-mixer/#/cctables/cctable/8,9" target="_blank">my personal music setup helper GUI</a>  

based on this data it would also be possible to create buttons or faders in any GUI and send the MIDI data directly to a specific channel

**Comment by benjaminfox** [comment]
Hey, thanks for the well-reasoned feedback.

> Formatting specific CC values/ranges with special meaning

Moving CC data to its own column, with consistent notation, is a very good idea. Let me know what you think of #64 . 

> Tons of variations in categories/sections

I noticed this too while adding the initial definitions, but I'm not sure how to approach it since synths love to push boundaries about this stuff. We came at it from the perspective of our app Condukt, which is a custom control surface for synths and a consistent CC organization structure is not required, and in general we want each definition to be very useful and specific to  its individual synth. I'll think about it. 

> my personal music setup helper GUI

This is much prettier than the project's website 😅 nice work!

**Comment by othmar52** [comment]
@benjaminfox  one last thought about the `usage` column of #64 ...  
Theoretically it is possible to create a generic GUI with the data of your csv's that has labelled faders, buttons or toggle switches.  
  
this line would create a fader element that sends from `0-127`  
`KORG,MS2000,Mixer,OSC 1 level,,20,,0,127,,,,,0-based,`  
  
this line would create an element like a toggle switch that sends `0` or `1`  
`Access,Virus A,Oscillators,Osc2 sync,,28,,0,1,,,,,0-based,0: Off; 1: On`  
  
those lines would create buttons with radio button behaviour  
`Access,Virus A,Filter,Filter1 mode,,51,,0,3,,,,,0-based,0: LP; 1: HP; 2: BP; 3: BS`  
`Moog,Minitaur,Envelopes,Trigger mode,73,,0,127,,,,,0-based,0-42: legato on; 43-84: legato off; 85-127: env gen reset`  

this line would create 3 radio buttons as well but with the limitation that most of the possible values can't be send with the generic GUI element, as each of the `Wave` value is different:  
`Access,Virus A,Oscillators,Osc1 wave select,,19,,0,64,,,,,0-based,1: Sine; 2: Triangle; 3-64: Wave`  
  
the reason is that there is no separation between `within a given range you will recieve the same result on every sent value` and `within a given range every value has another result`  

pretty sure the majority of ranges in this `usage` column always have the same result. So i wondered if those exceptions should be handeled with a different notation!? for example by replacing the range delimiter `X-Y` with `X<>Y`    

or do you think this is a confusing overhead?

**Comment by benjaminfox** [comment]
Oh that's a great point. That's bothered me too a few times. Sure, I like your notation suggestion for the exceptions where each value within the range is handled differently (volume, etc.). I'll open a ticket for documenting it.
