### ISSUE TITLE
Document the different range types for usage

### ISSUE THREAD

**Issue by benjaminfox** [usercamp/midi#65]
From @othmar52 in #62, let's document a notation for differentiating between usage ranges that are effectively switches and those that are effectively faders/encoders. 

 - `0-63: Off; 64-127: On` – here, the dashes between the numbers shows that every value within the range has equivalent functionality, like a discrete switch.
 - `0~127: Wave` – here, the tilde shows that the values between 0 and 127 will produce a different result (like volume increasing, envelope depth increasing, etc.), like a fader or endless encoder.

@othmar52 I thought about it a bit and I think the tilde is a good separator for these special ranges, let me know if that's workable for you :)

**Comment by othmar52** [comment]
@benjaminfox i agree! the tilde is way better than my suggestion

**Comment by fauxstor** [comment]
This looks good to me, please accept merge before I branch off to add another device!

**Comment by benjaminfox** [comment]
Right! @fauxstor I've documented the different notations for defining fader-like vs. switch-like ranges in the Usage column as per the discussion here.
